### ISSUE TITLE
Just two things

### ISSUE THREAD

**Issue by jakubszalek** [mczeplowski/react-graphql-playground#2]
Mateusz, at first, I'd like to say that I'm impressed with amount of work you put in our test task - it's a pleasure to check that kind of result :)

I found only two things that should be fixed:

1. One of unit tests is failing because of typo (Table.test.js) - 'No Data' / 'No data'
2. Unnecessary type assertion in `src/pages/index.tsx:40` - it is basically bad pattern and could be problematic in the future. I'd suggest to define mapping function which allow you to change the type without forcing it.

Feel free to reply and discuss if I'm missing anything.

Thanks!

**Comment by mczeplowski** [comment]
Hi @jakubszalek, glad to hear it, will do it today in the evening :)

**Comment by mczeplowski** [comment]
@jakubszalek  done, I know `as` is not good but didn't have time for typeguard but we have it now :D regarding failing test I have all green, but changed to case-insensitive's regexp :)
